-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATA, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE AS A
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'

UNION ALL

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATA, PRODUCT_ID, NULL, SALES_AMOUNT
FROM OFFLINE_SALE AS B
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'

ORDER BY 1 ASC, 2 ASC, 3 ASC